api:
  build: ./api
  ports:
  - "8080:8080"
client:
  build: ./client
  ports:
  - "80:3000"
  - "3000:3000"
  - "3001:3001"
  volumes:
  - ./client:/client
  links:
- api


#
#db:
#  build: ./db
#  ports:
#    - "3307:3306"
#
#api:
#  build: ./API
#  ports:
#    - "8080:8080"
#  volumes:
#    - ./API:/api
#  command: /bin/sh /api/start.sh
#  links:
#    - db
#
#client:
#  build: ./client
#  ports:
#    - "44200:4200"
#  volumes:
#    - ./client:/client
#  links:
#- api